# Generated by Django 4.0.6 on 2023-03-26 11:21

from django.db import migrations







class Migration(migrations.Migration):

    dependencies = [
        ('jiralike', '0001_initial'),
    ]

    operations = [
    ]
