# Generated by Django 4.0.6 on 2023-04-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jiralike', '0002_auto_20230326_1321'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='proj',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jiralike.project'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='proj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jiralike.project'),
        ),
    ]
