# Generated by Django 4.0.6 on 2023-03-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='types',
            field=models.CharField(choices=[('Bugs/errors', 'Bugs/errors'), ('Feature Requests', 'Feature Requests'), ('Other Comments', 'Other Comments')], default='Other Comments', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='types',
            field=models.CharField(choices=[('Bugs/errors', 'Bugs/errors'), ('Feature Requests', 'Feature Requests'), ('Other Comments', 'Other Comments')], default='Other Comments', max_length=30),
        ),
    ]
