# Generated by Django 4.0.6 on 2023-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_historicalticket_proj_alter_ticket_proj'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
